CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TYPE test_case_status AS ENUM ('DRAFT','STRUCTURING','REVIEW_REQUIRED','READY','STRUCTURE_FAILED','ARCHIVED');
CREATE TYPE execution_status AS ENUM ('QUEUED','PROVISIONING','RUNNING','WAITING_APPROVAL','CANCEL_REQUESTED','PASS','FAIL','BLOCKED','NEEDS_REVIEW','CANCELLED','SYSTEM_ERROR');
CREATE TYPE outbox_status AS ENUM ('PENDING','PUBLISHED','FAILED');

CREATE TABLE organizations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE users (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), email text NOT NULL, display_name text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE UNIQUE INDEX users_email_uq ON users (lower(email));
CREATE TABLE memberships (organization_id uuid NOT NULL REFERENCES organizations(id), user_id uuid NOT NULL REFERENCES users(id), role text NOT NULL, PRIMARY KEY (organization_id,user_id));
CREATE TABLE projects (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), project_key text NOT NULL, name text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(organization_id,project_key));
CREATE TABLE environments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), project_id uuid NOT NULL REFERENCES projects(id), name text NOT NULL, base_url text NOT NULL, allowed_domains jsonb NOT NULL DEFAULT '[]', viewport jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE test_cases (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), project_id uuid NOT NULL REFERENCES projects(id), display_id text NOT NULL, title text NOT NULL, group_name text NOT NULL DEFAULT 'General', created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(project_id,display_id));
CREATE TABLE test_case_versions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), test_case_id uuid NOT NULL REFERENCES test_cases(id), version_no integer NOT NULL, raw_text text NOT NULL, structured_spec jsonb, status test_case_status NOT NULL DEFAULT 'DRAFT', created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(test_case_id,version_no));
CREATE INDEX test_case_versions_status_idx ON test_case_versions(organization_id,status,created_at DESC);
CREATE TABLE test_accounts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), project_id uuid NOT NULL REFERENCES projects(id), name text NOT NULL, secret_ref text NOT NULL, status text NOT NULL DEFAULT 'AVAILABLE', created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(project_id,name));
CREATE TABLE executions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), project_id uuid NOT NULL REFERENCES projects(id), test_case_version_id uuid NOT NULL REFERENCES test_case_versions(id), environment_id uuid NOT NULL REFERENCES environments(id), account_id uuid REFERENCES test_accounts(id), idempotency_key text NOT NULL, status execution_status NOT NULL DEFAULT 'QUEUED', attempt integer NOT NULL DEFAULT 1, settings jsonb NOT NULL DEFAULT '{}', result jsonb, error_code text, parent_execution_id uuid REFERENCES executions(id), queued_at timestamptz NOT NULL DEFAULT now(), started_at timestamptz, ended_at timestamptz, UNIQUE(organization_id,idempotency_key));
CREATE INDEX executions_active_idx ON executions(organization_id,status,queued_at) WHERE status IN ('QUEUED','PROVISIONING','RUNNING','WAITING_APPROVAL','CANCEL_REQUESTED');
CREATE TABLE step_runs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), execution_id uuid NOT NULL REFERENCES executions(id) ON DELETE CASCADE, step_no integer NOT NULL, attempt integer NOT NULL DEFAULT 1, status text NOT NULL, action jsonb, assertion jsonb, confidence numeric(5,4), error_code text, started_at timestamptz, ended_at timestamptz, UNIQUE(execution_id,step_no,attempt));
CREATE TABLE artifacts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), execution_id uuid NOT NULL REFERENCES executions(id) ON DELETE CASCADE, step_run_id uuid REFERENCES step_runs(id) ON DELETE SET NULL, artifact_type text NOT NULL, object_key text NOT NULL, sha256 text NOT NULL, size_bytes bigint NOT NULL, expires_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX artifacts_retention_idx ON artifacts(expires_at) WHERE expires_at IS NOT NULL;
CREATE TABLE outbox_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), aggregate_type text NOT NULL, aggregate_id uuid NOT NULL, event_type text NOT NULL, payload jsonb NOT NULL, status outbox_status NOT NULL DEFAULT 'PENDING', attempts integer NOT NULL DEFAULT 0, available_at timestamptz NOT NULL DEFAULT now(), published_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX outbox_pending_idx ON outbox_events(status,available_at) WHERE status='PENDING';
CREATE TABLE audit_events (id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY, organization_id uuid NOT NULL REFERENCES organizations(id), actor_id uuid REFERENCES users(id), action text NOT NULL, resource_type text NOT NULL, resource_id text NOT NULL, request_id uuid NOT NULL, metadata jsonb NOT NULL DEFAULT '{}', occurred_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX audit_org_time_idx ON audit_events(organization_id,occurred_at DESC);
